{
 "title": "Wikimedia",
 "time": { "from": "2026-02-06T03:46:40.151Z", "to": "2026-02-06T03:56:26.566Z" },
 "panels": [
  {
   "title": "DLQ topic offset change rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(kafka_topic_partition_current_offset{topic=\"wikimedia.DLQ\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_topic_partitions{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Offset moving speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_consumergroup_current_offset{consumergroup=\"group\", topic=\"wikimedia_v4\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Msg VS outgoing Msg in KB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesoutpersec_total[1m])/ 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesinpersec_topic_wikimedia_v4_total[1m])/ 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "consumer group change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "changes(kafka_consumergroup_members{consumergroup=\"group\"}[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka_server_brokertopicmetrics_messagesinpersec_topic_wikimedia_v4_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesinpersec_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wikimedia Consumer Group Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=\"wikimedia_v4\", consumergroup=\"group\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_broker_info", "legendFormat": "__auto" }
   ]
  }
 ]
}